/**
 * Blog body blocks — the shape the admin builder writes and the public detail
 * page renders.
 *
 * A post body is an ordered array of blocks:
 *   { type: "intro"     , text }
 *   { type: "paragraph" , text }
 *   { type: "heading"   , text }
 *   { type: "list"      , items: [], ordered }
 *   { type: "quote"     , text, attribution }
 *   { type: "image"     , imageKey, imageUrl, caption }
 *
 * `body` (HTML) is still stored alongside `blocks`, generated by `blocksToHtml`,
 * so posts written before the builder — and anything that reads `body` — keep
 * working. `toBlocks()` is the one entry point that resolves either shape.
 */

export const BLOCK_TYPES = [
  {
    type: "intro",
    label: "Lead paragraph",
    hint: "Larger opening paragraph — usually the first block",
    placeholder: "Open the article with a sentence or two…",
  },
  {
    type: "paragraph",
    label: "Paragraph",
    hint: "Body text. Press Enter for a line break within the paragraph.",
    placeholder: "Write a paragraph…",
  },
  {
    type: "heading",
    label: "Heading",
    hint: "Section title",
    placeholder: "Section heading",
  },
  {
    type: "list",
    label: "Bullet list",
    hint: "One point per line",
    placeholder: "First point",
  },
  {
    type: "quote",
    label: "Quote",
    hint: "Pull quote, with an optional attribution",
    placeholder: "“A line worth pulling out of the article…”",
  },
  {
    type: "image",
    label: "Image",
    hint: "Sits full-width in the article, with an optional caption",
    placeholder: "",
  },
]

/* Stable client-side keys for the admin builder: array indices would remount an
 * input (losing focus) whenever a block moves, so each block carries a `_k`,
 * stripped again by cleanBlocks() before saving. */
let seq = 0
export const nextBlockKey = () => `b${++seq}`
export function withKeys(blocks) {
  return (blocks || []).map((b) => (b._k ? b : { ...b, _k: nextBlockKey() }))
}

export function blockMeta(type) {
  return BLOCK_TYPES.find((b) => b.type === type) || BLOCK_TYPES[1]
}

export function emptyBlock(type) {
  switch (type) {
    case "list":
      return { type, items: [""], ordered: false }
    case "quote":
      return { type, text: "", attribution: "" }
    case "image":
      return { type, imageKey: "", caption: "" }
    default:
      return { type, text: "" }
  }
}

/** True when a block carries nothing an editor would want saved. */
export function isEmptyBlock(b) {
  if (!b || !b.type) return true
  if (b.type === "list") return !(b.items || []).some((i) => i && i.trim())
  if (b.type === "image") return !b.imageKey && !b.imageUrl
  return !(b.text || "").trim()
}

/** Drop empties and editor-only fields (`_k`) before saving. */
export function cleanBlocks(blocks) {
  return (blocks || []).filter((b) => !isEmptyBlock(b)).map((b) => {
    const { _k, imageUrl, ...rest } = b // eslint-disable-line no-unused-vars
    if (rest.type === "list") {
      return { ...rest, items: (rest.items || []).map((i) => i.trim()).filter(Boolean) }
    }
    // A legacy HTML block can carry a bare src with no S3 key — keep that url.
    if (rest.type === "image" && !rest.imageKey && imageUrl) {
      return { ...rest, imageUrl }
    }
    return rest
  })
}

/* ── HTML ────────────────────────────────────────────────────────── */

const escapeHtml = (s = "") =>
  String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")

// Line breaks the author typed survive as <br> so the stored HTML matches what
// the block renderer shows (it uses whitespace-pre-line).
const withBreaks = (s = "") => escapeHtml(s).replace(/\n/g, "<br>")

/**
 * Render blocks to the HTML kept in `body`. This is a derived field — the
 * builder is the source of truth — but it keeps every existing consumer of
 * `body` (and any future export) working.
 */
export function blocksToHtml(blocks) {
  return (blocks || [])
    .filter((b) => !isEmptyBlock(b))
    .map((b) => {
      switch (b.type) {
        case "heading":
          return `<h2>${withBreaks(b.text)}</h2>`
        case "list": {
          const tag = b.ordered ? "ol" : "ul"
          const items = (b.items || [])
            .filter((i) => i && i.trim())
            .map((i) => `<li>${withBreaks(i)}</li>`)
            .join("")
          return `<${tag}>${items}</${tag}>`
        }
        case "quote":
          return b.attribution
            ? `<blockquote><p>${withBreaks(b.text)}</p><cite>${escapeHtml(b.attribution)}</cite></blockquote>`
            : `<blockquote><p>${withBreaks(b.text)}</p></blockquote>`
        case "image": {
          const src = b.imageUrl || b.imageKey || ""
          const img = `<img src="${escapeHtml(src)}" alt="${escapeHtml(b.caption || "")}">`
          return b.caption
            ? `<figure>${img}<figcaption>${escapeHtml(b.caption)}</figcaption></figure>`
            : `<figure>${img}</figure>`
        }
        default:
          return `<p>${withBreaks(b.text)}</p>`
      }
    })
    .join("\n")
}

const collapse = (s = "") =>
  s
    .replace(/[^\S\n]+/g, " ")
    .replace(/ *\n */g, "\n")
    .trim()

/**
 * Parse the HTML written before the builder existed back into blocks, so an old
 * post opens in the editor instead of as a wall of markup. Unknown markup is
 * kept as plain text rather than dropped.
 */
export function htmlToBlocks(html) {
  if (typeof html !== "string" || !html.trim()) return []

  // No DOM (SSR, tests) — fall back to blank-line splitting on the stripped text.
  if (typeof DOMParser === "undefined") {
    return collapse(html.replace(/<br\s*\/?>/gi, "\n").replace(/<[^>]+>/g, ""))
      .split(/\n\s*\n/)
      .map((t) => t.trim())
      .filter(Boolean)
      .map((text, i) => ({ type: i === 0 ? "intro" : "paragraph", text }))
  }

  const doc = new DOMParser().parseFromString(
    `<div id="root">${html.replace(/<br\s*\/?>/gi, "\n")}</div>`,
    "text/html"
  )
  const root = doc.getElementById("root")
  const blocks = []

  const pushText = (type, raw) => {
    const text = collapse(raw)
    if (text) blocks.push({ type, text })
  }

  for (const node of root.childNodes) {
    if (node.nodeType === 3) {
      // Untagged text — a blank line is a paragraph break, which is how the
      // plain-text bodies written before any of this were meant to read.
      collapse(node.textContent)
        .split(/\n\s*\n/)
        .forEach((t) => pushText("paragraph", t))
      continue
    }
    if (node.nodeType !== 1) continue
    const tag = node.tagName.toLowerCase()

    if (/^h[1-6]$/.test(tag)) {
      pushText("heading", node.textContent)
    } else if (tag === "ul" || tag === "ol") {
      const items = [...node.querySelectorAll("li")]
        .map((li) => collapse(li.textContent))
        .filter(Boolean)
      if (items.length) blocks.push({ type: "list", items, ordered: tag === "ol" })
    } else if (tag === "blockquote") {
      const cite = node.querySelector("cite")
      const attribution = cite ? collapse(cite.textContent) : ""
      if (cite) cite.remove()
      const text = collapse(node.textContent)
      if (text) blocks.push({ type: "quote", text, attribution })
    } else if (tag === "figure" || tag === "img") {
      const img = tag === "img" ? node : node.querySelector("img")
      const cap = tag === "figure" ? node.querySelector("figcaption") : null
      if (img?.getAttribute("src")) {
        blocks.push({
          type: "image",
          imageKey: "",
          imageUrl: img.getAttribute("src"),
          caption: cap ? collapse(cap.textContent) : collapse(img.getAttribute("alt") || ""),
        })
      }
    } else {
      pushText("paragraph", node.textContent)
    }
  }

  // The first paragraph of a legacy post read as the lead — keep it looking that
  // way, matching how these posts rendered before the builder.
  const firstPara = blocks.find((b) => b.type === "paragraph")
  if (firstPara && blocks.indexOf(firstPara) === 0) firstPara.type = "intro"

  return blocks
}

/**
 * Resolve whatever a post carries into blocks: the builder's array when present,
 * otherwise the legacy HTML/plain-text `body`. Returns undefined when there is
 * nothing to render, so callers can fall back.
 */
export function toBlocks(body) {
  if (Array.isArray(body)) {
    const kept = body.filter((b) => !isEmptyBlock(b))
    return kept.length ? kept : undefined
  }
  const parsed = htmlToBlocks(body)
  return parsed.length ? parsed : undefined
}
